openapi: '3.0.2'
info:
  title: Rocket Chat API
  version: '1.0'
components:
  securitySchemes:
    userid:
      type: apiKey
      in: header
      name: x-user-id
    token:
      type: apiKey
      in: header
      name: x-auth-token
paths:
  /groups.addAll:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.addModerator:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.addOwner:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.addLeader:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.archive:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.close:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.counters:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.create:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.delete:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.files:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.getIntegrations:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.history:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.info:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.invite:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.kick:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.leave:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.list:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.listAll:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.members:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.messages:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.online:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.open:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.removeModerator:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.removeOwner:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.removeLeader:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.rename:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.setCustomFields:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.setDescription:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.setPurpose:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.setReadOnly:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.setTopic:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.setType:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.setAnnouncement:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.unarchive:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.roles:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.moderators:
    get:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.setEncrypted:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
  /groups.convertToTeam:
    post:
      security:
        - userid: []
          token: []
      responses:
        '200':
          description: OK
